### ISSUE TITLE
[Security Whitepaper] Ambiguous sentence

### ISSUE THREAD

**Issue by JDGrimes** [Automattic/Documattic#11]
Under the *A2 - Broken Authentication and Session Management* heading is [this](https://github.com/Automattic/Documattic/blob/master/WordPress-Security-White-Paper/WordPressSecurityWhitePaper.html#L86):

>WordPress core software manages user accounts and authentication and details such as the user ID, name, and password are managed on the server-side, as well as the authentication cookies.

I *think* it is intended to mean this:

>WordPress core software manages user accounts and authentication**,** and details such as the user ID, name, and password are managed on the server-side, as **as are** the authentication cookies.

But it could also mean this:

>WordPress core software manages user accounts and authentication and details such as the user ID, name, and password on the server-side, as well as the authentication cookies.

**Comment by sararosso** [comment]
Hi there! Thanks for your feedback - we've moved the white paper over to the WordPress repo, so we'd really love this to be re-submitted there! Thanks :) 
https://github.com/WordPress/Security-White-Paper
