### ISSUE TITLE
Duplicates and missing footnotes

### ISSUE THREAD

**Issue by BoiteAWeb** [Automattic/Documattic#7]
Hey
1 footnote is duplicated, this results as a missing of 1 footnote.
Thanks

**Comment by sararosso** [comment]
Can you be more specific? :D Which ones are missing? In the HTML version?

**Comment by BoiteAWeb** [comment]
https://raw.githubusercontent.com/Automattic/Documattic/master/WordPress-Security-White-Paper/WordPressSecurityWhitePaper.html

We got footnote 1, 2, 3, 3 (dup and ref missing) etc
So we got 30 footnotes but only 29 link at the bottom.

**Comment by sararosso** [comment]
Hi there! Thanks for your feedback - we've moved the white paper over to the WordPress repo, so we'd really love this to be re-submitted there! Thanks :) 
https://github.com/WordPress/Security-White-Paper
